### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by moussetc**
- Add `/gifs` command to allow preview and shuffle
- Add Gfycat as another GIF Provider
- Rename plugin from `Giphy plugin` to `GIF commands` to better reflect reality
- Invisible stuff (after a rebase on mattermost-plugin-sample):
  - use Go modules rather than godep
  - multiplatform executable
  - refactor files
  - unit tests
  - Giphy: don't rely on an external library (obsolete)
  - Giphy : use the `/search` API rather than `/translate`
  - errors are more verbose and, hopefully, helpful

TODO before merging:

- [x] Fix Travis CI. Oops.

- [x] Adress issue where Gfycat link provokes an 'Access denied' errors on some gifs (don't use the content_urls in the Gfycat response, use the previous level properties which seem to be better populated)

- [x] ~~Add FreeBSD support to the multiplatform executable. Somehow.~~ Deported to #14 

- [x] Integration tests with a scratch new MM server

- [x] Update README 

- [ ] Self code review

- [ ] Ask MM team on how to update plugin name in https://integrations.mattermost.com. Goal: being referenced for "GIF", "command" and "Giphy".

### CODE REVIEW

**Comment by patrickgalbraith** [comment]
Getting a lot of these errors after updating.

```
{"level":"error","ts":1561508770.6392667,"caller":"mlog/log.go:172","msg":"Unable to get GIF URL","path":"/api/v4/commands/execute","request_id":"5o6b5i5mo7yd9qnks78pq8qwhc","ip_addr":"10.1.1.58","user_id":"55ddwgp5bbbeumpjjbpxnkc4ro","method":"POST","err_where":"Giphy Plugin","http_code":400,"err_details":"Giphy Plugin: No match found, "}
```

It seems to happen when you search using spaces, like this:

```
/gifs star wars
```

**Comment by patrickgalbraith** [comment]
Just wanted to add that we are using our own API key, not the public one and these settings:

image

**Comment by patrickgalbraith** [comment]
I've enabled the mattermost image proxy and it seems to work a bit better now.

**Comment by moussetc** [comment]
Thank you for reporting this issue. I noticed it, including for single-word request if I remember well).
When you say "work a bit better", do you mean that the bug has stopped, or that it is less frequent?

**Comment by patrickgalbraith** [comment]
Seems to have stopped for now. Not sure why that would be though since it worked fine before we upgraded the plugin and the proxy was disabled then.

**Comment by moussetc** [comment]
Looks like the Giphy bugs that were plaguing this new version were due to the Giphy API itself : https://github.com/Giphy/GiphyAPI/issues/197 ...

**Pull request merged**
