### PR TITLE
Style: add a color to the send button

### PR DESCRIPTION
**Pull request by thomasruiz**
Improve the user experience by adding a color to the "Send" button.

### CODE REVIEW

**Comment by thomasruiz** [comment]
Hm, the build is failing probably because the mattermost-server dependency is outdated. I am not quite sure the implications of updating it.

**Comment by moussetc** [comment]
Thanks for your contribution! 

The ability to style a button was introduced in Mattermost server 5.24.0, so to add this nice modification, you'll have to do some more modifications, if you're up to it:
- update `mattermost-server` dependency in go.mod (do commit the resulting go.sum changes as well!)
- update `min_server_version` in plugin.json
- run `make apply` and commit the resulting changes to server/manifest.go

And when this feature is integrated into a new release, I'll have to remember to
- update the example image on the README (demo_preview.png) so show those colored buttons
- update the server/plugin compatibility table in the README

**Comment by thomasruiz** [comment]
@moussetc It is done!

**Comment by moussetc** [comment]
Thanks for the edits, it's a nice change :ok_hand: 
Seeing the UI change with my own eyes got me to think that the Shuffle button shouldn't be gray, as it's the second most important action (I don't know about you, but I shuffle _a lot_). I'm gathering user inputs, I'll do the edit in another commit when my mind is made up :)

**Pull request merged**
